default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.25.13

images:
  - k8s.gcr.io/ingress-nginx/controller:v0.41.2@sha256:1f4f402b9c14f3ae92b11ada1dfe9893a88f0faeb0b2f4b903e2c67a0c3bf0de
  - docker.io/jettech/kube-webhook-certgen:v1.5.0
