default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.25.12

images:
  - k8s.gcr.io/ingress-nginx/controller:v1.0.0@sha256:0851b34f69f69352bf168e6ccf30e1e20714a264ab1ecd1933e4d8c0fc3215c6
